# Generated by Django 5.1.1 on 2024-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
